title: Yaoyi Cai's Homepage
page-top-title: Yaoyi Cai
top-section-bg-text: Artificial Intelligence and Machine Vision Technology
home-subtitle: Yaoyi Cai&ensp;|&ensp;蔡耀仪
copyright-text: '&copy; Yaoyi Cai 2023-2025. All Rights Reserved.'
